title: "yooDev"
description: "ì›¹ê°œë°œìì´ì í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œìë¥¼ ì§€í–¥í•˜ëŠ” ê°œë°œìì˜ ë¸”ë¡œê·¸"
url: "https://yoo94.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: "&#127968; Home"
    url: /
  - text: "&#128203; Blog"
    url: /blog
#  - text: "&#128400; About"
#    url: /about
  - text: "ğŸ”’ policy"
    url: /projects
  - text: "&#128211; GuestBook"
    url: /guestBook

seo:
  type: "website"
  image: "/assets/img/profile.png" # ì‚¬ì´íŠ¸ë¥¼ ëŒ€í‘œí•˜ëŠ” ì´ë¯¸ì§€

# Author details
author_logo: "profile.png"
author: "yoo94"
author_name: "ìœ ì¬ì„"
author_bio: "ì›¹ ê°œë°œì ìœ ì¬ì„ì…ë‹ˆë‹¤."
author_email: "jaeseok9405@gmail.com"
author_location: "KOREA SEOUL"
author_website_url: "https://yoo94.github.io"
typewrite-text: "ê°œë°œê³¼ ì‚¬ìš©ìì—ê²Œ ì¢‹ì€ uxë¥¼ ì œê³µí•˜ê³ ì‹¶ì–´í•˜ëŠ” ì›¹ê°œë°œìì…ë‹ˆë‹¤."
hero_cover_img: "cover.jpeg" # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  - company_name: "&#127970; íšŒê³„ì†”ë£¨ì…˜ì—…ì²´ (ìœ ë‹ˆ**)"
    company_url: "&#128053; https://unipost.co.kr/portal"
    designation: "&#128197; 2021. 04 ~ ì¬ì§ì¤‘"
    description: "&#128204; requireJs ê¸°ë°˜ (AMDëª¨ë“ˆ ë¡œë”) ì†”ë£¨ì…˜ ê°œë°œ"
    description2: "&#128204; react-native,typescript ëª¨ë°”ì¼ ì†”ë£¨ì…˜ ê°œë°œ"
    description3: "&#128204; linux,window OS ê¸°ë°˜ ì„œë²„ ì†”ë£¨ì…˜ ì„¤ì¹˜ ë° ìœ ì§€ ë³´ìˆ˜"
    description4: "&#128204; ë³¸ì‚¬ ì›¹ ì†”ë£¨ì…˜ js -> ts ë§ˆì´ê·¸ë ˆì´ì…˜ ì§„í–‰"
    visibility: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-0S5KXL30HJ"
    anonymize_ip: false

# Education
author_education_details:
  - college_name: "&#127979; fast campus innercircle 1st period"
    college_degree: "&#128197; 2024. 07 ~ 2024. 11"
    description2: "&#128204; 3ë…„ì°¨ ì´ìƒ ê°œë°œ ì—­ëŸ‰ í–¥ìƒ,front-end ê°œë°œìë¡œ ì§€ì›"
    description: "&#128204; ë¼ì´ë¸ŒëŸ¬ë¦¬, í”„ë¡œì íŠ¸ ì§„í–‰"
    visibility: true
  - college_name: "&#127979; ë¨¸ì‹ ëŸ¬ë‹ê¸°ë°˜ SWê°œë°œì"
    college_degree: "&#128197; 2020. 09 ~ 2021. 03"
    description2: "&#128204; ê²½ì˜ê¸°ìˆ ê°œë°œì› êµìœ¡ì„¼í„°"
    description: "&#128204; js , html ,css / java , jsp , spring , mysql , oracle"
    visibility: true
  - college_name: "&#127979; í•œêµ­ ë°©ì†¡í†µì‹  ëŒ€í•™êµ"
    college_degree: "&#128197; 2023.03.02 - 2025.02"
    description: "&#128204; ì»´í“¨í„° ê³¼í•™ê³¼"
    visibility: true
  - college_name: "&#127979; í•œêµ­ ê´€ê´‘ ëŒ€í•™êµ"
    college_degree: "&#128197; 2013.03.04 - 2017.02.16"
    description: "&#128204; ê´€ê´‘ ê²½ì˜í•™ê³¼"
    visibility: true

# Projects
author_project_details:
  - project_title: "&#128421; ì°¨ì„¸ëŒ€ ëª¨ë°”ì¼ ì†”ë£¨ì…˜ ê°œë°œ ì°¸ì—¬"
    project_info: "&#128343; 23.09 ~ 24.01"
    project_description: "&#128203; reactì™€ typeScriptë¥¼ ì´ìš©í•œ ì „í‘œì‘ì„± í™”ë©´ì„ ë‹´ë‹¹"
    project_description2: "&#128204; front &#128312; react-native, react, typeScript, redux, webpack"
    project_description3: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; ì‚¬ì¡°CPK (ë¦¬ì•¡íŠ¸ ë„¤ì´í‹°ë¸Œ ì›¹ì•±)"
    project_info: "&#128343; 24.03.04 ~ 24.07.31 / ìœˆë„ìš° ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; ì „ìê²°ì¬ ì„œë¹„ìŠ¤ ê¸°ëŠ¥ ì»¤ìŠ¤í„°ë§ˆì´ì§•"
    project_description2: "&#128204; front &#128312; react-native, react, typeScript, redux, webpack"
    project_description3: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; HMM (ë¦¬ì•¡íŠ¸ ë„¤ì´í‹°ë¸Œ ì›¹ì•±)"
    project_info: "&#128343; 24.12.01 ~ 25.02.28 / aws linux ì„¤ì¹˜"
    project_description: "&#128203; ì „ìê²°ì¬ ì„œë¹„ìŠ¤ ê¸°ëŠ¥ êµ¬í˜„"
    project_description2: "&#128203; ì „í‘œì‘ì„± ì„œë¹„ìŠ¤ ê¸°ëŠ¥ ê°„ì†Œí™” êµ¬í˜„"
    project_description3: "&#128204; front &#128312; react-native, react, typeScript, redux, webpack"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; HMM (ì›¹)"
    project_info: "&#128343; 24.02 ~ 25.01 / aws linux ì„¤ì¹˜"
    project_description: "&#128203; í•´ì™¸/êµ­ë‚´ ì¶œì¥ë¹„ ë³´ê³ ì„œ, ì •ì‚° ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description2: "&#128203; aws s3 ì—°ë™ ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; í‹°ë§µ ëª¨ë¹Œë¦¬í‹° (ì›¹)"
    project_info: "&#128343; 23.06.01 ~ 24.02.01 / aws linux ì„¤ì¹˜"
    project_description: "&#128203; ê±°ë˜ì²˜ ë“±ë¡ ì„œë¹„ìŠ¤ / ì¶œì¥ë¹„ ì •ì‚° ì„œë¹„ìŠ¤"
    project_description2: "&#128203; ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ API êµ¬í˜„"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; SK ì‹œê·¸ë„· (ì›¹)"
    project_info: "&#128343; 23.01.16 ~ 23.07.21 / aws linux ì„¤ì¹˜"
    project_description: "&#128203; ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ API / SSO ì¸ì¦ ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description2: "&#128203; ì›¹ì·¨ì•½ì  ì¡°ì¹˜"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; ë‚¨í•´í™”í•™ (ì›¹)"
    project_info: "&#128343; 22.08.25 ~ 23.05.05 / ìœˆë„ìš° ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ API êµ¬í˜„"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; SK ìŠ¤í† ì•„ (ì›¹ / ì›¹ì•±)"
    project_info: "&#128343; 22.04.15 ~ 22.10.03 / centOS ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; ë”ì¡´ ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ API / ì¶œì¥ë¹„ ì •ì‚° ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description2: "&#128203; ëª¨ë°”ì¼ ë¬¸ì 2ì°¨ì¸ì¦ êµ¬í˜„ / ì•„íŒŒì¹˜ ì›¹ì„œë²„ ì„¤ì¹˜ ë° was í†µì‹  ì—°ê²°"
    project_description3: "&#128204; front web &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; front mobile &#128312; html, css, js, jquery, cordova"
    project_description5: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; SK ë°”ì´ì˜¤íŒœ (ì›¹)"
    project_info: "&#128343; 22.02.14 ~ 22.07.31 / ìœˆë„ìš° ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; ì‹¤ë¹„ ì •ì‚° ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description2: "&#128203; ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ ë° AD sso ì¸ì¦ ì„œë¹„ìŠ¤ êµ¬í˜„"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; í•œí™” ì—ë„ˆì§€ ì†”ë£¨ì…˜ ê³ ë„í™” (ì›¹)"
    project_info: "&#128343; 22.02.07 ~ 22.07.08 / centOS ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; AS-IS ê¸°ëŠ¥ ê³ ë„í™” ì§„í–‰"
    project_description2: "&#128203; ê·¸ë¦¬ë“œ ë¼ì´ë¸ŒëŸ¬ë¦¬ ë³€ê²½ìœ¼ë¡œ ì¸í•œ ê³ ë„í™”"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true
  - project_title: "&#128421; ë§¤ê·¸ë‚˜ì¹© ë°˜ë„ì²´ ì†”ë£¨ì…˜ ê³ ë„í™” (ì›¹)"
    project_info: "&#128343; 21.08.02 ~ 22.01.21 / ìœˆë„ìš° ì„œë²„ ì„¤ì¹˜"
    project_description: "&#128203; ê·¸ë£¹ì›¨ì–´ ê²°ì¬ì—°ë™ API êµ¬í˜„"
    project_description2: "&#128203; ì¶œì¥ë¹„ ì„œë¹„ìŠ¤ ê¸°ëŠ¥ êµ¬í˜„"
    project_description3: "&#128204; front &#128312; html, css, js, jquery, requireJs, mustache"
    project_description4: "&#128204; back &#128313; java,spring"
    visibility: true

# Social links
github_username: "yoo94"
wakatime_username: "yoo94"

# Contact form - (choose formspress or getform)
formspree_email: "jaeseok9405@gmail.com"

# Releases - widget can be (sidebar, modal or embed)
olvy_organization: "devlopr"
olvy_widget_type: "sidebar"

# Syntax highlighter
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# Pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# Minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: "archive"
  permalinks:
    category: "/category/:name/"

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: "/:path/:basename:output_ext"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: "/blog/authors/:slug"
  - scope:
      path: "assets/**"
    values:
      sitemap: true

# Build settings
plugins:
  - "jekyll-paginate"
  - "jekyll-gist"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"
  - "jekyll-admin"
  - "jekyll-feed"

# Jekyll Admin Config
jekyll_admin:
  homepage: "posts"

# Exclude from processing
exclude:
  - ".sass-cache/"
  - ".jekyll-cache/"
  - "gemfiles/"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "assets/bower_components/isotope-layout/README.md"
  - "assets/bower_components/icono/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md"
  - "assets/bower_components/ghosthunter/README.md"
  - "assets/bower_components/nanobar/README.md"
  - "assets/bower_components/lightgallery/demo/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md"
  - "assets/bower_components/jquery-mousewheel/README.md"
  - "assets/bower_components/get-size/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md"
  - "assets/bower_components/jquery-mousewheel/ChangeLog/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md"
  - "assets/bower_components/desandro-matches-selector/README.md"
  - "assets/bower_components/ev-emitter/README.md"
  - "assets/bower_components/font-awesome/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md"
  - "assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md"
  - "assets/bower_components/ghosthunter/example/Index.html"
  - "assets/bower_components/lightgallery/test/lightgallery.html"
  - "assets/bower_components/masonry-layout/README.md"
  - "assets/bower_components/imagesloaded/README.md"

destination: "./build"
future: true
